### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by evpobr**

### CODE REVIEW

**Comment by erikd** [comment]
As I understand it, ALSA only exists for Linux and sndio only for OpenBSD. That may make things easier.

**Comment by evpobr** [comment]
@erikd No, sndio Linux port exists. I found `libsndio6.1` package in my Ubuntu repository.

**Comment by syb0rg** [comment]
What does this PR change exactly?

**Comment by evpobr** [comment]
@syb0rg Oops, it happens when i tried to merge branches. Nothing to do here.

**Pull request closed without merging**
